image: node:16.18.0-buster

pages:
  stage: build
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm run docs:build --base "/$CI_PROJECT_NAME/"
  artifacts:
    paths:
      - public
  only:
    - main
